apiVersion: app.fybrik.io/v1alpha1
kind: FybrikModule
metadata:
  name: airbyte-module
  labels:
    name: airbyte-module
    version: latest # semantic version
spec:
  type: service
  chart:
    name: ghcr.io/cdoron/airbyte-module-chart:0.0.0
    values:
      image.tag: 0.0.0
  capabilities:
    - capability: read
      scope: workload
      api:
        connection:
          name: fybrik-airbyte
          fybrik-airbyte:
            hostname: "{{ .Release.Name }}.{{ .Release.Namespace }}"
            port: "80"
            scheme: grpc
      supportedInterfaces:
        - source:
            protocol: airbyte-postgres
            dataformat: json
        - source:
            protocol: airbyte-mysql
            dataformat: json
        - source:
            protocol: airbyte-google-sheets
            dataformat: json
        - source:
            protocol: airbyte-us-census
            dataformat: json
