apiVersion: app.fybrik.io/v1alpha1
kind: FybrikModule
metadata:
  name: airbyte-module
  labels:
    name: airbyte-module
    version: latest # semantic version
spec:
  type: service
  chart:
    name: ghcr.io/cdoron/airbyte-module-chart:0.0.0
    values:
      image.tag: master
  capabilities:
    - capability: read
      scope: workload
      api:
        connection:
          name: fybrik-airbyte
          fybrik-airbyte:
            hostname: "{{ .Release.Name }}.{{ .Release.Namespace }}"
            port: 80
            scheme: grpc
      supportedInterfaces:
        - source:
            protocol: s3
            dataformat: parquet
        - source:
            protocol: s3
            dataformat: csv
      actions:
        - name: RedactAction
        - name: RemoveAction
