apiVersion: app.fybrik.io/v1alpha1
kind: FybrikModule
metadata:
  name: arrow-flight-module
  labels:
    name: arrow-flight-module
    version: latest # semantic version
spec:
  type: service
  chart:
    name: ghcr.io/cdoron/arrow-flight-module-chart:0.0.0
    values:
      image.tag: master
  capabilities:
    - capability: transform
      scope: workload
      api:
        connection:
          name: fybrik-arrow-flight
          fybrik-arrow-flight:
            hostname: "{{ .Release.Name }}.{{ .Release.Namespace }}"
            port: "80"
            scheme: grpc
      supportedInterfaces:
        - source:
            protocol: fybrik-arrow-flight
      actions:
        - name: FilterAction
