apiVersion: v1 
kind: Pod 
metadata: 
    name: airbyte-module
spec:
  volumes:
  - name: docker-socket
    emptyDir: {}
  - name: json-dir
    emptyDir: {}
  - name: config
    configMap:
      name: abm-cm
  containers:
  - name: docker
    image: ghcr.io/cdoron/airbyte-module:0.0.0
    volumeMounts:
    - name: docker-socket
      mountPath: /var/run
    - name: json-dir
      mountPath: /json
    - name: config
      mountPath: /etc/conf
      readOnly: true
  - name: docker-daemon
    image: docker:20.10.7-dind
    securityContext:
      privileged: true
    volumeMounts:
    - name: docker-socket
      mountPath: /var/run
    - name: json-dir
      mountPath: /json
