apiVersion: v1 
kind: Pod 
metadata: 
    name: dind
spec:
  volumes:
  - name: docker-socket
    emptyDir: {}
  - name: json-dir
    emptyDir: {}
  containers:
  - name: docker
    image: docker:20.10.7
    command:
    - sleep
    args:
    - 99d
    volumeMounts:
    - name: docker-socket
      mountPath: /var/run
    - name: json-dir
      mountPath: /json
  - name: docker-daemon
    image: docker:20.10.7-dind
    securityContext:
      privileged: true
    volumeMounts:
    - name: docker-socket
      mountPath: /var/run
    - name: json-dir
      mountPath: /json
