app-uuid: {{ .Values.uuid | default "app-uuid-missing" }}
{{ if .Values.assets -}}
data:
{{- range .Values.assets }}
  - name: {{ .assetID | quote }}
{{- toYaml .source | nindent 4 }}
{{- end -}}
{{- else -}}
data: []
{{- end -}}
